core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'
urlpatterns = [
    path('', views.home_ka, name = 'home_ka'),
    path('news/ka/json', views.news_ka_json, name = 'news_ka_json'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaocna/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    thumbnail = models.ImageField(upload_to='news_thumbnails')
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "News"

core/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *

# Create your views here.
def home_ka(request):
    return render(request, 'ka/home-ka.html', {
        'recent_news': News.objects.all().order_by('-date')[:5]
    })
    


def news_ka_json(request):
    news = News.objects.all().order_by('-date')
    news_list = list(news.values('id', 'title', 'date', 'thumbnail', 'content'))
    
    for item in news_list:
        item['thumbnail'] = News.objects.get(id = item['id']).thumbnail.url
        item['date'] = item['date'].strftime('%d/%m/%Y')
        
    return JsonResponse(news_list, safe=False)

core/templates/ka/home-ka.html
{% extends "ka/widget-ka.html" %}
{% load static %}

{% block title %} მთავარი - ჩრდილოეთ ამერიკის ქართული ეპარქია {% endblock %}

{% block extra_css %} 
    <link rel="stylesheet" href="{% static 'css/pages/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive/home.css' %}">
{% endblock %}

{% block center-panel %}    
    <section class="news-carousel-panel">
        <div class="news-carousel-slide">
            <nav class="carousel-navigation" id="carousel-navigation">
                <button class="carousel-btn" id="prev">
                    <i class="bi bi-caret-left-fill"></i>
                </button>
                <button class="carousel-btn" id="next">
                    <i class="bi bi-caret-right-fill"></i>
                </button>
            </nav>
            <div class="news-container" id="news-container">
            
            </div>
            <div class="carousel-indicators" id="carousel-indicators">
            </div>
            <script src="{% static 'js/news-carousel-slide.js' %}"></script>
        </div>
    </section>
{% endblock %}

core/templates/ka/layout-ka.html
{% load static %}
<!DOCTYPE html>
<html lang="ka">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'icons/logo.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/pages/layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive/layout.css' %}">
        {% block css %} {% endblock %}
    </head>
    <body>
        <nav class="navbar" id="navbar">
            <a href="{% url 'core:home_ka' %}" class="navbar-logo">
                <img src="{% static 'images/logos/logo-extended-ka.png' %}" alt="Site Logo" class="navbar-logo-img">
            </a>
            <ul class="navbar-menu" id="navbar-menu">
                <a href="{% url 'core:home_ka' %}" class="navbar-menu-logo">
                    <img src="{% static 'images/logos/logo.png' %}" alt="Site Logo" class="navbar-menu-logo-img">
                </a>
                <li class="navbar-item">
                    <a href="{% url 'core:home_ka' %}" class="navbar-link">მთავარი</a>
                </li>
                <li class="navbar-item dropdown">
                    <a class="navbar-link">საქართველოს ეკლესია <i class="bi bi-caret-down-fill arrow"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" class="dropdown-menu-link">ისტორია</a></li>
                        <li><a href="#" class="dropdown-menu-link">პატრიარქი</a></li>
                        <li><a href="#" class="dropdown-menu-link">წმინდა სინოდი</a></li>
                    </ul>
                </li>
                <li class="navbar-item dropdown">
                    <a class="navbar-link">ეპარქია<i class="bi bi-caret-down-fill arrow"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" class="dropdown-menu-link">ეპარქიის ისტორია</a></li>
                        <li><a href="#" class="dropdown-menu-link">მღვდელმთავარი</a></li>
                        <li><a href="#" class="dropdown-menu-link">სამრევლოები</a></li>
                        <li><a href="#" class="dropdown-menu-link">მონასტრები</a></li>
                        <li><a href="#" class="dropdown-menu-link">სამღვდელოება</a></li>
                        <li><a href="#" class="dropdown-menu-link">სამთავარხუცესო</a></li>
                        <li><a href="#" class="dropdown-menu-link">საეპიტროპოსოები</a></li>
                        <li><a href="#" class="dropdown-menu-link">სამდივნო</a></li>
                        <li><a href="#" class="dropdown-menu-link">ადმინისტრაციული საბჭო</a></li>
                        <li><a href="#" class="dropdown-menu-link">დირექტორთა საბჭო</a></li>
                        <li><a href="#" class="dropdown-menu-link">საეკლესიო სასამართლო</a></li>
                        <li><a href="#" class="dropdown-menu-link">ეპარქიის დოკუმენტები</a></li>
                    </ul>
                </li>
                <li class="navbar-item">
                    <a href="#" class="navbar-link">კონტაქტი</a>
                </li>
                <li class="navbar-item navbar-item-special">
                    <a href="#" class="navbar-link">შესაწირი</a>
                </li>
                <a href="/en" class="translator">
                    <img src="{% static 'images/flags/united-states.png' %}" alt="united-states-flag">
                </a>
            </ul>
            <button class="navbar-toggler" id="navbar-toggler" aria-label="Toggle navigation">
                <i class="bi bi-list"></i>
            </button>
            <script src="{% static 'js/navbar.js' %}"></script>
        </nav>
        <div class="social-media-icons" id="social-media-icons">
            <a href="https://www.facebook.com/profile.php?id=100064567997597" target="_blank">
                <i class="bi bi-facebook soc-media-icon" id="facebook"></i>
            </a>
            <a href="https://www.instagram.com/gaocna/" target="_blank">
                <i class="bi bi-instagram soc-media-icon" id="instagram"></i>
            </a>
            <a href="https://www.youtube.com/@georgianapostolicorthodoxc342/featured" target="_blank">
                <i class="bi bi-youtube soc-media-icon" id="youtube"></i>
            </a>
        </div>
        <main class="main-content">
            {% block main %} 
            {% endblock %}
        </main>
        <footer class="footer">
            <div class="copyright">
                <p>ჩრდილოეთ ამერიკის ქართული ეპარქია <span lang="en">&copy; 2024</span> ყველა უფლება დაცულია</p>
            </div>
        </footer>
    </body>
</html>

core/templates/ka/widget-ka.html
{% extends "ka/layout-ka.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'css/pages/widget.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive/widget.css' %}">
    {% block extra_css %} {% endblock %}
{% endblock %}

{% block main %}    
    <section class="widgets-panel">
        <article class="widget">
            <header class="widget-header">
                სათაური 1
            </header>
            <div class="widget-body">
                <div class="widget-image-container">
                    <img src="{% static 'images/test/widget-test.jpg' %}" alt="სურათი">
                </div>
            </div>
        </article>
        <article class="widget">
            <header class="widget-header">
                სათაური 2
            </header>
            <div class="widget-body">
                <div class="widget-image-container">
                    <img src="{% static 'images/test/widget-test-2.jpeg' %}" alt="სურათი">
                </div>
            </div>
        </article>
        <article class="widget">
            <header class="widget-header">
                სათაური 3
            </header>
            <div class="widget-body">
            </div>
        </article>
    </section>
    <div class="center-panel">
        {% block center-panel %} {% endblock %}
    </div>
    <aside class="widgets-panel">
        <article class="widget">
            <header class="widget-header">
                სათაური 4
            </header>
            <div class="widget-body">
            </div>
        </article>
        <article class="widget">
            <header class="widget-header">
                სათაური 5
            </header>
            <div class="widget-body">
            </div>
        </article>
        <article class="widget">
            <header class="widget-header">
                სათაური 6
            </header>
            <div class="widget-body">
            </div>
        </article>
    </aside>
{% endblock %}